### PR TITLE
Fix for cc 2.5.94+

### PR DESCRIPTION
**Pull request by bartam1**
| Q               | A      |
| --------------- | ------ |
| Bug fix?        | yes |
| New feature?    | no |
| API breaks?     | no|
| Deprecations?   | yes |
| License         | Apache 2.0 |

### What's in this PR?
After release [2.5.94](https://github.com/linkedin/cruise-control/releases/tag/2.5.94), cruise control uses a double field for the number of cores used in host load and broker load responses instead of int ([PR-1839](https://github.com/linkedin/cruise-control/pull/1839)). The go-cruise-control client still uses an int field (see [here](https://github.com/banzaicloud/go-cruise-control/blob/b616ae1133669bc3cbc40369c693aab1a0764bc2/pkg/types/broker_stats.go#L91)).

### Checklist

- [x] Implementation tested
- [x] Tested against Cruise Control version: x.y.z (if applicable)
- [x] User guide and development docs updated (if needed)

### CODE REVIEW

**Review by hong6914 — DISMISSED** [review]

**Review by pregnor — COMMENTED** [review]
**Question**: Does changing the HostLoadStats fields brake backward compatibility of go-cruise-control's public API?

**Review by pregnor — DISMISSED** [review]
Nevermind my question, I did a quick search, it looks like Koperator is the sole public consumer of this package, so we should indicate the breaking change IMO in v0.2.0 and we are going to be fine to support newer CC versions.

**Comment by amuraru** [comment]
@pregnor is this a breaking change though? Old cc versions should be supported as well as an int can be parsed as float iiuc

**Comment by bartam1** [comment]
> @pregnor is this a breaking change though? Old cc versions should be supported as well as an int can be parsed as float iiuc

What is the advantage to support older CC versions with newer Koperator?

**Review by pregnor — APPROVED** [review]

**Review by Kuvesz — APPROVED** [review]
I guess this is fine, maybe we could handle older CC versions on the Koperator side?

**Pull request merged**
